export const GET_WEBSITE_CONFIG = '@GLOBAL/GET_WEBSITE_CONFIG';
export const GET_WEBSITE_CONFIG_SUCCESS = '@GLOBAL/GET_WEBSITE_CONFIG_SUCCESS';
export const GET_WEBSITE_CONFIG_FAIL = '@GLOBAL/GET_WEBSITE_CONFIG_FAIL';
export const LOAD_PAGE_FAIL = '@GLOBAL/LOAD_PAGE_FAIL';
