export const GET_WEBSITE_CONFIG = '@GLOBAL/GET_WEBSITE_CONFIG';
export const GET_WEBSITE_CONFIG_SUCCESS = '@GLOBAL/GET_WEBSITE_CONFIG_SUCCESS';
export const GET_WEBSITE_CONFIG_FAIL = '@GLOBAL/GET_WEBSITE_CONFIG_FAIL';
